# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LinaWolf\FormDoubleOptIn\:
    resource: '../Classes/*'

  LinaWolf\FormDoubleOptIn\Upgrades\FormDoubleOptInNamespaceMigrationUpgradeWizard:
    tags:
      - name: install.upgradewizard
